CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   fullname TEXT NOT NULL,
   username TEXT NOT NULL,
   email TEXT NOT NULL,
   password TEXT NOT NULL,
   is_admin BOOLEAN NOT NULL DEFAULT FALSE,

   CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX users_username_key ON users (username);
CREATE UNIQUE INDEX users_email_key ON users (email);
